config/routes.rb
Rails.application.routes.draw do
  get '/blogs' => 'home#index'
  post '/blogs' => 'home#create'
  get 'blogs/new' => 'home#new', as: 'new_form'
  get 'blogs/:id' => 'home#show', as: 'blog'
  get '/blogs/:id/edit' => 'home#edit', as: 'edit'
  patch '/blogs/:id' => 'home#update'
  delete '/blogs/:id' => 'home#destroy', as: 'delete_blog'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true,
  uniqueness: {scope: :title},
  length: {scope: :title, minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @blogs = Blog.all
end

def show
  @blog = Blog.find(params[:id])
end

def new
  @blog = Blog.new
end

def create
  @blog = Blog.create(form_params)
  if @blog.valid?
    redirect_to blogs_path
  end
end

def edit
  @blog = Blog.find(params[:id])
end

def update
  @blog = Blog.find(params[:id])
  @blog.update(form_params)
  if @blog.valid?
    redirect_to blogs_path
  end
end

def destroy
  @blog = Blog.find(params[:id])
  if @blog.destroy
    redirect_to blogs_path
  end
end

private
  def form_params
    params.require(:blog).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit.html.erb
<h1> Update Your Post </h1>
<%= form_with model: @blog, method: :patch do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br/>
  <%= form.label :content %>
  <%= form.text_area :content %>
  <br/>
  <%= form.submit 'Edit Post'%>
<% end %>
<%= link_to 'Back to post', blog_path %>

app/views/home/index.html.erb
<h1> Moesha's Diary Part II </h1>
  <% @blogs.each do |blog| %>
    <h3> <li> <%= link_to blog.title, blog_path(blog) %> </li> </h3>
  <% end %>
<br/>
<%= link_to 'Create a new blog post', new_form_path %>

app/views/home/new.html.erb
<h3> Create a new blog post </h3>

<%= form_with model: @blog do |form| %>
  <%= form.label :title %> :
  <br/>
  <%= form.text_field :title %>
  <br/>
  <br/>
  <%= form.label :content %>
  <br/>
  <%= form.text_area :content %>
  <br/>
  <br/>
  <%= form.submit 'Submit your entry' %>
<% end %>

app/views/home/show.html.erb
<h2> <%= @blog.title %> </h2>
<h4> <%= @blog.content %> </h4>
<br/>

<%= link_to 'Edit Post', edit_path %>
<br/>
<%= button_to 'Delete Post', delete_blog_path, method: :delete %>
<br/>
<%= link_to 'Back to all posts', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>